### ISSUE TITLE
from-docx problem

### ISSUE THREAD

**Issue by welblaud** [TEIC/Stylesheets#308]
I need to use conversion from docx to tei xml. I had no problems until I tried to work with the last version of Stylesheets. When I try to use `make`, only two tests fail: 1) xelatex, which I don’t need, 2) docxtotei, which is what I need very much.

I guess there is no problem with paths and saxon, because everything runs well except this.

The testing process logs:

```
BUILD FAILED
/opt/appx/Stylesheets/docx/build-from.xml:33: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:414)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:299)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:850)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:388)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
make[1]: *** [test-from-docx] Error 1
```

**Comment by martindholmes** [comment]
I just ran the from-docx tests in the master branch, the dev branch, the 7.43 release branch and the 7.44 upcoming release branch, and I see no problems. Could you describe exactly what setup you're using, and how you run the conversion?

**Comment by welblaud** [comment]
Ma Java:
```
/opt/appx/Stylesheets $ java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```
As for the Saxon, it is installed on the machine too. I know it is included in the Stylesheets project but don’t know if the doubled presence of it could cause such things.

If I try to convert a test file:
```
/opt/appx/Stylesheets $ bin/docxtotei --profile=simple tmp/test.docx tmp/test.xml
WARNING: No localsource set. Will get a copy from http://www.tei-c.org/Vault/P5/.
Convert test.docx to /opt/appx/Stylesheets/tmp/test.xml (docx to tei) using profile simple
     [echo]      using /opt/appx/Stylesheets/profiles/simple/docx/from.xsl

BUILD FAILED
/opt/appx/Stylesheets/docx/build-from.xml:33: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:414)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:299)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:850)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:388)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

Now, if I try to simply use `make`, all tests run well except the `from-docx`:
```
BUILD: testing from-docx
../bin/docxtotei test-indexes.docx temp.xml
WARNING: No localsource set. Will get a copy from http://www.tei-c.org/Vault/P5/.
Convert test-indexes.docx to /opt/appx/Stylesheets/Test/temp.xml (docx to tei) using profile default
     [echo]      using /opt/appx/Stylesheets/profiles/default/docx/from.xsl

BUILD FAILED
/opt/appx/Stylesheets/docx/build-from.xml:33: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:414)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:299)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:850)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:388)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
make[1]: *** [test-from-docx] Error 1
```

I have no idea what are basic steps expected from the user at the beginning. Whether I should run `make` as an admin or no etc.

**Comment by martindholmes** [comment]
You don't need to be root to run any of this. Could you try this, from the Stylesheets folder?

cd Test
make test-from-docx

and post what happens? Also, what version of the Stylesheets do you have? You should be able to read it in the file "VERSION" which is in the root Stylesheets directory.

**Comment by welblaud** [comment]
Thank you,
my version is 7.44.0a

Here is the test log:
```
/opt/appx/Stylesheets/Test $ make test-from-docx
BUILD: testing from-docx
../bin/docxtotei test-indexes.docx temp.xml
WARNING: No localsource set. Will get a copy from http://www.tei-c.org/Vault/P5/.
Convert test-indexes.docx to /opt/appx/Stylesheets/Test/temp.xml (docx to tei) using profile default
     [echo]      using /opt/appx/Stylesheets/profiles/default/docx/from.xsl

BUILD FAILED
/opt/appx/Stylesheets/docx/build-from.xml:33: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:414)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:247)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:299)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:317)
        at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:178)
        at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:850)
        at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:388)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
make: *** [test-from-docx] Error 1

```

**Comment by martindholmes** [comment]
I think I see something suspicious here in the docx/build-from.xml file:

~~~~~
<target name="convert">
    <echo>	 using ${docxtoTEI}</echo>
    <unzip src="${inputFile}" dest="${outputTempDir}"/>
    <xslt force="yes" style="${docxtoTEI}" in="${outputTempDir}/word/document.xml" out="${outputFile}">
      <xmlcatalog>
        <catalogpath>
          <pathelement location="$catalogfile"/>
        </catalogpath>
      </xmlcatalog>
      <factory name="net.sf.saxon.TransformerFactoryImpl"/>
      <classpath location="${oxygenlib}/saxon9ee.jar"/>
      <param name="word-directory" expression="file:///${outputTempDir}"/>
      <param name="inputDir" expression="${inputDir}"/>
      <param name="mediaDir" expression="word/media"/>
    </xslt>
  </target>
~~~~~

What's that hard-coded dependency on Oxygen and SaxonEE doing there? Perhaps if you don't have Oxygen on your system, that's the root of the problem.

If I comment out the classpath line in that file, it still works fine for me. Could you try that and see if it solves the problem for you?

**Comment by welblaud** [comment]
Yes, commenting out the classpath line works for me! Thank you!

**Comment by martindholmes** [comment]
I've committed a fix to the dev branch (commit 30ee9138). This ticket can be closed if nothing breaks as a result.

**Comment by peterstadler** [comment]
I was about to close the issue but found that there are more conversion scripts that feature a reference to saxon9ee.jar:

* docbook/build-from.xml
* odt/build-from.xml
* slides/build-to.xml
* tcp/build-from.xml
* xlsx/build-from.xml

and there is `Test/Makefile` which has a target `test-pureant` which seems to be dependent on saxon9ee?!

That said, I totally agree that we should not hard-code such dependencies to non-free software and I'm pretty sure that we can simply remove the offending lines as @martindholmes did for docx. I'm just to tired now to go on …

**Comment by tuurma** [comment]
Following PS list of files to clean up now...
