### ISSUE TITLE
build fails because of xi:inlcude

### ISSUE THREAD

**Issue by ttasovac** [TEIC/Stylesheets#431]
My transformation fails because of `xi:inlcude` (my odd file includes "chapters" and each chapter includes examples from a different file). 

```
bin/teitorelaxng --odd /Users/ttasovac/Development/ttasovac-forks/lexicalresources/Schemas/TEILex0/TEILex0.odd tei_lex0.rng
WARNING: No localsource set. Will get a copy from https://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml if necessary.
Convert TEILex0.odd to /Users/ttasovac/Downloads/stylesheets/tei_lex0.rng (tei to relaxng) using profile default
     [echo] Do ODD expand processing (schema ) 

BUILD FAILED
/Users/ttasovac/Downloads/stylesheets/relaxng/build-to.xml:29: The following error occurred while executing this line:
/Users/ttasovac/Downloads/stylesheets/common/teianttasks.xml:386: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:/Users/ttasovac/Development/ttasovac-forks/lexicalresources/Schemas/TEILex0/TEILex0.odd; lineNumber: 31; columnNumber: 107; Error attempting to parse XML file (href='TEILex0.odd.parts/01__introduction.xml'). Reason: An include with href '../TEILex0.odd.examples/TEILex0-examples.stripped.xml'failed, and no fallback element was found.

```
This same transformation works when I run it from oXygen. I tried adding the oxygenlib paramater but then the error is even more mysterious for me:

```
bin/teitorelaxng --odd --oxygenlib=/Applications/Oxygen\ XML\ Editor/lib /Users/ttasovac/Development/ttasovac-forks/lexicalresources/Schemas/TEILex0/TEILex0.odd tei_lex0.rng
WARNING: No localsource set. Will get a copy from https://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml if necessary.
Convert TEILex0.odd to /Users/ttasovac/Downloads/stylesheets/tei_lex0.rng (tei to relaxng) using profile default

BUILD FAILED
Target "XML" does not exist in the project "teitorelaxng". 
```

I'm at a bit of a loss here because, like many people, I guess, I've been relying on doing transformations in oXygen for years, well, decades really. We're not that young anymore. 

Many thanks in advance for your tips and suggestions!

All best,
Toma

**Comment by lb42** [comment]
Is this because of the way relative URLs are being calculated?

**Comment by sydb** [comment]
@ttasovac —

Is this still a problem?

**Comment by ttasovac** [comment]
Yes. I just tried again, after updating the TEI Stylesheets. The included files in our odd don't seem to be found. I'm including the full error output.

```
⋊> ~/D/D/T/Stylesheets on dev ◦ bin/teitorelaxng --odd /Users/ttasovac/Development/DARIAH/lexicalresources/Schemas/TEILex0/TEILex0.odd tei_lex0.rng
WARNING: No localsource set. Will get a copy from /Users/ttasovac/Development/DARIAH/TEI-C/Stylesheets/source/p5subset.xml if necessary.
Convert TEILex0.odd to /Users/ttasovac/Development/DARIAH/TEI-C/Stylesheets/tei_lex0.rng (tei to relaxng) using profile default
     [echo] Do ODD expand processing (schema ) 

BUILD FAILED
/Users/ttasovac/Development/DARIAH/TEI-C/Stylesheets/relaxng/build-to.xml:29: The following error occurred while executing this line:
/Users/ttasovac/Development/DARIAH/TEI-C/Stylesheets/common/teianttasks.xml:388: java.lang.AssertionError: Fatal error during transformation using /Users/ttasovac/Development/DARIAH/TEI-C/Stylesheets/odds/odd2odd.xsl:  Error reported by XML parser: An include with href 'TEILex0.parts/01__introduction.xml'failed, and no fallback element was found.; SystemID: file:/Users/ttasovac/Development/DARIAH/lexicalresources/Schemas/TEILex0/TEILex0.odd; Line#: 173; Column#: 42
	at net.sf.saxon.lib.StandardErrorHandler.reportError(StandardErrorHandler.java:108)
	at net.sf.saxon.lib.StandardErrorHandler.fatalError(StandardErrorHandler.java:87)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.reportError(XIncludeHandler.java:2521)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.reportFatalError(XIncludeHandler.java:2516)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.reportFatalError(XIncludeHandler.java:2512)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.emptyElement(XIncludeHandler.java:1037)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2725)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	at net.sf.saxon.event.Sender.send(Sender.java:142)
	at net.sf.saxon.Controller.makeSourceTree(Controller.java:1311)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:335)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:74)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:201)
	at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:870)
	at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:408)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.base/java.util.Vector.forEach(Vector.java:1359)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:827)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: Fatal error during transformation using /Users/ttasovac/Development/DARIAH/TEI-C/Stylesheets/odds/odd2odd.xsl:  Error reported by XML parser: An include with href 'TEILex0.parts/01__introduction.xml'failed, and no fallback element was found.; SystemID: file:/Users/ttasovac/Development/DARIAH/lexicalresources/Schemas/TEILex0/TEILex0.odd; Line#: 173; Column#: 42
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.fatalError(TraXLiaison.java:535)
	at net.sf.saxon.lib.ErrorReporterToListener.report(ErrorReporterToListener.java:68)
	at net.sf.saxon.lib.StandardErrorHandler.reportError(StandardErrorHandler.java:105)
	... 57 more
Caused by: net.sf.saxon.trans.XPathException:  Error reported by XML parser: An include with href 'TEILex0.parts/01__introduction.xml'failed, and no fallback element was found.
	at net.sf.saxon.trans.XPathException.fromXmlProcessingError(XPathException.java:178)
	at net.sf.saxon.lib.ErrorReporterToListener.report(ErrorReporterToListener.java:64)
	... 58 more
```

**Comment by sydb** [comment]
Yeah. OK. So I do and do not know why this is happening, and can (at the moment) only suggest a work-around, not a fix.

The ant code is requesting XInclude processing from Saxon. (See file [common/teianttasks.xml](https://github.com/TEIC/Stylesheets/blob/2456660de90509af62603436b587b3d99d3c8c47/common/teianttasks.xml) line [390](https://github.com/TEIC/Stylesheets/blob/2456660de90509af62603436b587b3d99d3c8c47/common/teianttasks.xml#L390).) I do not know if it is requesting it properly or not. (I am not completely clear on how Saxon [handles XInclude](https://www.saxonica.com/documentation10/index.html#!sourcedocs/XInclude). Your [lexicalresources/Schemas/TEILex0/TEILex0.odd](https://github.com/DARIAH-ERIC/lexicalresources/blob/master/Schemas/TEILex0/TEILex0.odd) file includes lots of other files, and uses the `@xpointer` attribute of the `<xi:include>` to specify which bit to include, using [shorthand pointers](https://www.w3.org/TR/2003/REC-xptr-framework-20030325/#shorthand). (But note, I tried changing them to the [element scheme](https://www.w3.org/TR/xptr-element/), and got the same failure.)

So the problem is, I believe, that Saxon is not properly processing the `@xpointer`. I do not know if that’s a problem with Saxon, a documented limitation of Saxon, or a problem with how we are calling it from ant. Thus I do not really know how to fix it. (I suppose we should ask on the Saxon mailing list.)

But I do know how to work around it: perform XInclude processing before ODD processing, using an XInclude processor that will handle the `@xpointer` attributes. E.g.:
~~~sh
$ cd lexicalresources/Schemas/
$ xmllint --xinclude TEILex0/TEILex0.odd > TEILex0/TEILex0_full.odd
$ /path/to/Stylesheets/bin/teitorelaxng TEILex0/TEILex0_full.odd
$ rm TEILex0/TEILex_full.odd
$ mv TEILex0/TEILex0_full.odd.relaxng TEILex0/TEILex0.rng
~~~
(Note: `xmllint` needs to have been compiled with the XInclude feature. I have never seen a version of `xmllint` on any of my GNU/Linux or MacOS systems that does _not_ have XInclude capability, and I almost always just use the package manager.)

**Comment by sydb** [comment]
Responses from the [saxon-help](https://saxon.markmail.org/search/?q=date%3A2021%20XInclude%20XPointer) mailing list were informative, but may not really solve your problem. The basic gist is that Saxon uses the built-in Java XML parser[1,2], so it seems the problem lies in the Java parser. Some other folks get around this using either [`xmllint`](http://xmlsoft.org/index.html) or Norm Walsh’s [`sinclude`](https://github.com/ndw/sinclude) to perform XInclude processing as a pre-processing step. (And there is, of course, an XProc 3 step to do this: `<p:xinclude>`; I have never tested how well it handles `@xpointer`.)

-----
##### footnotes
[1] Which is Xerces, I think?
[2] You can write your own parser as a Java class and ask Saxon to use it with the -x switch.

**Comment by sydb** [comment]
Not sure there is much more to say or do here, @ttasovac. If so, feel free to re-open.

**Comment by hcayless** [comment]
Xerces will do XInclude, just not by default. Is there no way to allow it to be switched on as a parameter? I haven't looked at this at all, I should say...

**Comment by lb42** [comment]
Saxon will do xinvlude too but you have to pass it the right parameter. I think the problem here is that the teitoxxxx commands don't have an - xi lparameter?

**Comment by sydb** [comment]
IIRC, Saxon _is_ performing XInclude for OP, just not properly handline the `@xpointer` attribute of the `<xi:include>`.

**Comment by lb42** [comment]
Ah OK. Have now read the thread more carefully amd see I am talking nonsense.
